[versions]
kotlin = "2.1.0"
firework = "2.1.0-firework.32"
compose = "1.7.3"
coroutines = "1.10.0"
kotlinxDatetime = "0.6.1"
ktor = "3.0.1"
slf4j = "2.0.16"
androidGradlePlugin = "8.7.1"
junit = "5.11.3"
javassist = "3.30.2-GA"
logback = "1.5.9"
asm = "9.7.1"
evas = "1.2.0-RC"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

evas = { module = "io.sellmair:evas", version.ref = "evas" }
evas-compose = { module = "io.sellmair:evas-compose", version.ref = "evas" }

compose-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
