[versions]
kotlin = "2.0.21"
compose = "1.7.0"
coroutines = "1.9.0"
ktor = "3.0.0"
slf4j = "2.0.16"
androidGradlePlugin = "8.5.2"
junit = "5.10.1"
javassist = "3.30.2-GA"
logback = "1.5.9"
jewel = "0.26.1"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jewel-ide = { module = "org.jetbrains.jewel:jewel-ide-laf-bridge-242", version.ref = "jewel" }

ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktorNetwork = { module = "io.ktor:ktor-network", version.ref = "ktor" }

compose-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }


junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }