name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan


      - name: Cache Grade Test Home
        uses: actions/cache@v4
        with:
          path: |
            functionalTests/build/gradleHome
          key: ${{ runner.os }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run 'check'
        run: ./gradlew check --scan

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: '**/build/reports/'

      - name: Upload actual test data
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: actual-test-data
          path: '**/*-actual*'

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run Macos Integration Tests
        run: ./gradlew check -Phost-integration-tests=true --scan

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports-macos
          path: '**/build/reports/'

      - name: Upload actual test data
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: actual-test-data-macos
          path: '**/*-actual*'

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Setup git
        run: git config --system core.longpaths true

      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run Windows Integration Tests
        run: ./gradlew check -Phost-integration-tests=true --scan

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports-windows
          path: '**/build/reports/'

      - name: Upload actual test data
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: actual-test-data-windows
          path: '**/*-actual*'


  compile-samples:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run 'check'
        working-directory: samples/counter
        run: ./gradlew check --scan

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports-samples
          path: '**/build/reports/'
