name: Deploy Dev Build
on:
  workflow_dispatch:
jobs:
  publish:
    environment: deploy
    env:
      ORG_GRADLE_PROJECT_signing.key: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signing.key.password: ${{ secrets.SIGNING_PASSWORD }}

    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Cache Kotlin Native
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan
          restore-keys: ${{ runner.os }}-konan

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: 'true'

      - name: Publish Locally
        run: ./gradlew publishLocally
        env:
          ORG_GRADLE_PROJECT_signing.key: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signing.key.password: ${{ secrets.SIGNING_PASSWORD }}

      - name: Publish To Firework Repository
        run: ./gradlew publishAllPublicationsToFireworkRepository --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_fireworkUsername: ${{ secrets.FIREWORK_USERNAME }}
          ORG_GRADLE_PROJECT_fireworkPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Publish To Sellmair Repository
        run: ./gradlew publishAllPublicationsToSellmairRepository --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_repo.sellmair.user: ${{ secrets.SELLMAIR_USERNAME }}
          ORG_GRADLE_PROJECT_repo.sellmair.password: ${{ secrets.SELLMAIR_PASSWORD }}
